# Generated by Django 2.2.10 on 2020-03-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feed',
        ),
    ]
